csvFilesPathEmpty = [{
                'id':'',
                'name':'',
                'Last Modified':'',
                'GDPR Data Processing note':'',
                'GDPR Data Processing note modifiedby':'',
                'Business Description':'',
                'Business Description modifiedBy':'',
                'Resource Type':'',
                'description':'',
                'Resource Name':'',
                
                }]
csvFilesFileNameEmpty = [{
                'id':'',
                'Last Modified':'',
                'Loading Mode':'',
                'Notes':'',
                'Data Historicization':'',
                'Frequency':'',
                'Feeding':'',
                'Transformation':'',
                'GDPR Data Processing note':'',
                'GDPR Data Processing note modifiedBy':'',
                'Data Quality Link':'',
                'Data Quality Link modifiedBy':'',
                'Business Description':'',
                'Business Description modifiedBy':'',
                'Resource Name':'',
                'Name':'',
                'description':'',
                'path id':'',
                'Acronym': ''
                }]
csvFilesColumnEmpty = [{
                'id':'',
                'name':'',
                'Last Modified':'',
                'Field Primary Key':'',
                'Field Offset':'',
                'Field ODBC Format':'',
                'Field Mandatory':'',
                'Notes':'',
                'Algorithm':'',
                'Field Unique Index':'',
                'Field Position':'',
                'Record Type':'',
                'Field Length':'',
                'Data Flow Type':'',
                'Field Domain Table':'',
                'Function':'',
                'Field Data Format':'',
                'Field Decimals':'',
                'Key Data Element':'',
                'Key Data Element modifiedBy':'',
                'GDPR Data Processing note':'',
                'GDPR Data Processing note modifiedBy':'',
                'Data Quality Link':'',
                'Data Quality Link modifiedBy':'',
                'Asset Classification':'',
                'Asset Classification modifiedBy':'',
                'Business Description':'',
                'Business Description modifiedBy':'',
                'Resource Name':'',
                'description':'',
                'File id':''
                }]
