#!/bin/bash

#
# Check the README.md file before run.
# Last update: 16/01/2023
#

LOG_DIR="$HOME/autopatch/logs"

# write the output of the script to a log file
# The -a flag tells tee to append to the file rather than overwriting it
# The -i flag tells tee to ignore the interrupt signal (CTRL-C)
exec &> >(tee -ai "$LOG_DIR/stop-$(date -d "today" +"%Y-%m-%d").log")

NSRVS=$($AXON_BASE/axonhome/third-party-app/scripts/axonStatus | awk '/ 1 / {print}' | wc -l)
printf '%s: N.SERVICES: %s\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")" "$NSRVS"

# if Axon is down, I will start it...
if [ "$NSRVS" -gt 0 ]
then
    # note: we check the status before running the startup because the command 
    # will restart the Axon services 
    $AXON_BASE/bin/shutdown.sh

    NSRVS=$($AXON_BASE/axonhome/third-party-app/scripts/axonStatus | awk '/ 1 / {print}' | wc -l)
    printf '%s: N.SERVICES: %s\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")" "$NSRVS"

    if [ "$NSRVS" -eq 0 ]
    then
        # all services are down
        NSRVS_OUT=$($AXON_BASE/axonhome/third-party-app/scripts/axonStatus)
        printf '%s: All configured services are down:\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"
        printf '%s\n' "$NSRVS_OUT"

        exit 0

    else
        # some service have problems during shutdown, with status 1 or -1
        NSRVS_OUT=$($AXON_BASE/axonhome/third-party-app/scripts/axonStatus | awk 'NR==5 || !/ 0 / {print}')
        printf '%s: Some services report some issues during startup:\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"
        printf '%s\n' "$NSRVS_OUT"

        exit 1
    
    fi

fi

printf '%s: Axon is already stopped.\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"

exit 0
