#!/bin/bash

# NOTE: exit status is 0 if OK, 1 if minor problem, 2 if serious problem.

DDM_HOME="/informatica/ddm992"
LOG_DIR="$HOME/autopatch/logs"

# write the output of the script to a log file
# The -a flag tells tee to append to the file rather than overwriting it
# The -i flag tells tee to ignore the interrupt signal (CTRL-C)
exec &> >(tee -ai "$LOG_DIR/ddm_start-$(date -d "today" +"%Y-%m-%d").log")

# Start the DDM server
# https://docs.informatica.com/data-security-group/dynamic-data-masking/9-9-3/administrator-guide/server-control/server-commands/start.html
#
# Using the DDM server command:
#"$DDM_HOME"/server start &> /dev/null
#
# If you configured the SystemD command:
systemctl start infaddm > /dev/null

# Check the status of the DDM server
sleep 60s
"$DDM_HOME"/server status > /dev/null

# 0 = server UP
if [ "$?" = "0" ]; then
    printf '%s: Script exit with success (exit code = 0).\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"
    printf '%s: Server status: %s\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")" "$?"

    exit 0

else
    printf '%s: Script exit with error (exit code = 1).\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"
    printf '%s: Chech the server.log file for details:\n' "$(date -d "today" +"%Y-%m-%d %H:%M:%S")"
    tail -n10 "$DDM_HOME/log/server.log"
    printf '\n'

    exit 1

fi
